### PR TITLE
Add config for specific Promise constructor

### PR DESCRIPTION
**Pull request by ertrzyiks**
Hey,
to avoid mixing promise libraries we can be adaptive and use constructor provided by user and then fallback to bluebird.

### CODE REVIEW

**Comment by krzychukula** [comment]
Can you add info about it in Readme?

**Comment by ertrzyiks** [comment]
@krzychukula sure, updated

**Comment by jakubwasilewski** [comment]
Hi, everything checks out - thanks for the PR. 

The only thing I might change when it's time to release is the default implementation. The situation has changed since good-guy-http was originally implemented and Node 4.x+ now has a native Promise -which should probably be the default when available instead of bluebird.

**Comment by kjarmicki** [comment]
Akshully ;) native Promises were available since 0.12, even without --harmony flag, so it's safe to use that without forcing clients to jump onto 4.x bandwagon

**Comment by jakubwasilewski** [comment]
No forcing necessary - we'll just use native Promise if available, and
require('bluebird') if not. So me misremembering the actual version is
irrelevant :).

On Fri, Jan 29, 2016 at 3:02 PM, Krystian Jarmicki <notifications@github.com

> wrote:
> 
> Akshully ;) native Promises were available since 0.12, even without
> --harmony flag, so it's safe to use that without forcing clients to jump
> onto 4.x bandwagon
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Schibsted-Tech-Polska/good-guy-http/pull/1#issuecomment-176766993
> .

## 

[image: Opis: Schibsted]

_Software engineer_
_Jakub Wasilewski_
Schibsted Tech Polska

jakub.wasilewski@schibsted.pl

+48 721 812 013
www.schibsted.pl _www.facebook.com/SchibstedTechPolska
http://www.facebook.com/SchibstedTechPolska_

**Comment by kjarmicki** [comment]
yay :+1:

**Pull request merged**
